import React from "react";
import CarouselControlled from "../../../components/Carousel";

const apiEndpointSlides = [
  {
    id: "endpoint-summary",
    title: "API Endpoint Summary",
    summary:
      "SonicDNA API covers catalog, ingest, conversion, re-conversion, and audio streaming for preview/playback.",
    description: `Endpoint groups:
  GET  /api/get-audio
    List source tracks + computed labels for picker UI

  POST /api/submit-audio
    Upload source track and persist metadata/profile

  POST /api/convert-audio/:audioFileId
    Convert imported target file using selected source profile

  POST /api/reconvert-audio/:audioFileId
    Re-run conversion with manual BPM/pitch/gain values

  GET  /api/stream-audio/:audioFileId
    Stream stored source audio from R2

  GET  /api/stream-temp-audio/:filename
    Stream temporary converted WAV for preview`,
  },
  {
    id: "get-audio",
    title: "GET /api/get-audio",
    summary:
      "Returns the source-audio catalog used to populate selection dropdowns in Lab.",
    description: `What it does:
  - Reads source files from object storage
  - Joins metadata + analysis from Postgres
  - Returns picker-ready audio list

Returns:
  { message, audioFiles: SoundProfile[] }`,
  },
  {
    id: "submit-audio",
    title: "POST /api/submit-audio",
    summary:
      "Uploads source audio and creates a persisted sound profile for selection in Lab.",
    description: `What it does:
  - Accepts multipart audio upload
  - Stores file in Cloudflare R2
  - Saves metadata + profile in Postgres

Client use:
  Refresh source list after successful upload`,
  },
  {
    id: "convert-audio",
    title: "POST /api/convert-audio/:audioFileId",
    summary:
      "Converts imported target audio using selected source DNA profile and returns conversion settings.",
    description: `What it does:
  - Analyzes imported target audio
  - Builds auto conversion plan from source profile
  - Writes temporary converted WAV for preview

Returns:
  { convertedAudioUri, conversionPlan }`,
  },
  {
    id: "reconvert-audio",
    title: "POST /api/reconvert-audio/:audioFileId",
    summary:
      "Re-runs conversion with user-adjusted sliders for BPM, pitch, and gain.",
    description: `Inputs:
  targetBPM, pitchShiftSemitones, gainDb, importedTempoBpm

What it does:
  - Applies user override settings
  - Re-runs conversion against same source/target
  - Returns updated convertedAudioUri`,
  },
  {
    id: "stream-source-audio",
    title: "GET /api/stream-audio/:audioFileId",
    summary:
      "Streams stored source audio from Cloudflare R2 by database audioFile ID.",
    description: `Use case:
  Source preview playback

What it does:
  - Resolves storage key from DB record
  - Reads object from R2
  - Streams bytes to client player`,
  },
  {
    id: "stream-temp-audio",
    title: "GET /api/stream-temp-audio/:filename",
    summary:
      "Streams converted WAV files from server temp storage for instant preview.",
    description: `Use case:
  Preview converted output before share/export

What it does:
  - Serves temp WAV generated by convert/reconvert
  - Enables low-latency playback in app`,
  },
];

const ApiEndpointSection = () => {
  return (
    <div className="tw-relative lg:tw-w-8/12 tw-flex tw-justify-center md:tw-items-center md:tw-justify-normal">
      <div className="tw-w-full tw-mx-auto">
        <CarouselControlled
          wireframeslides={apiEndpointSlides}
          width="100%"
          height="auto"
        />
      </div>
    </div>
  );
};

export default ApiEndpointSection;
