import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "bootstrap/dist/css/bootstrap.min.css";
import './custom.scss';
import localFont from 'next/font/local';


const boldonse = localFont({
  src: './fonts/Boldonse-Regular.ttf',
  variable: '--font-boldonse',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={boldonse.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
