import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./custom.scss";
import localFont from "next/font/local";

const boldonse = localFont({
  src: "./fonts/Boldonse-Regular.ttf",
  variable: "--font-boldonse",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={boldonse.variable}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
